document.getElementById("eliminar").addEventListener("click",()=>{
$("#delete").modal("show")
})
document.getElementById("editar").addEventListener("click",()=>{
$("#edit").modal("show")
})
document.getElementById("activar").addEventListener("click",()=>{
$("#activar1").modal("show")
})
